### ISSUE TITLE
issues with recursive without `depth`

### ISSUE THREAD

**Issue by gabrielcsapo** [s0ph1e/node-website-scraper#105]
```
var scraper = require('website-scraper');
var options = {
  urls: ['http://nodejs.org/'],
  directory: __dirname + '/nodejs.org',
  recursive: true
};

// or with promise
scraper.scrape(options).then(function (result) {
    console.log(result);
});
```

this code causes `Segmentation fault: 11` will dig into the code see if any memory can be freed or written to a cache file to be retrieved later.

**Comment by s0ph1e** [comment]
Hello 

You are trying to download whole internet ;) That's why it is not working
It is said in documentation
> Don't forget to set maxDepth to avoid infinite downloading

Url can be saved **only** after all its children resources are saved (and children resources of children and so on). If you don't specify `maxDepth` it will follow anchors infinitely - so all children resources will never be saved. 

It is expected behavior. Need to set `maxDepth` (and maybe `urlFilter` to limit downloading to _nodejs.org_ domain, for example).
