### ISSUE TITLE
doesn't download images where path is in JS file

### ISSUE THREAD

**Issue by buildcave** [s0ph1e/node-website-scraper#115]
Hey there! Thanks for making such a rad tool :)

I've found that if an image path is in a javascript file the scraper doesn't download the image.

Here is an example URL: http://womenshealth.com-yourarticles.co/breaking-news/angelina.html

The comment images are not downloaded because the paths are loaded at runtime via a local JSON file (comments.js)

Would love to hear your thoughts, thanks!

**Comment by s0ph1e** [comment]
Hi @buildcave

This module doesn't execute js files, it only saves them as is. That's why resources loaded by js will not be saved.
All it does is parsing html and css files. So only static site can be downloaded for now

I have no plans to add it in nearest future
All I can suggest is to use phantomjs/prerender before scraper if it makes sense

**Comment by buildcave** [comment]
ok, I can figure out another way. Appreciate the help !
