### ISSUE TITLE
links inherit the protocol they are ripped from when they are "//"

### ISSUE THREAD

**Issue by talfstad** [s0ph1e/node-website-scraper#121]
Hey sOph1e,

This is an enhancement, not a bug. Also I'm not completely sure it's in the scope of this project, but wanted to see what you thought:

When pulling site down that is hosted on https and has its links specified as '//' (which inherit https when hosted on https), it would be nice if '//' was replaced with the protocol 'https://'. In other words, just inherit the protocol for all links of the resource being downloaded.

So when someone downloads the site but not the resources, the resources are unavailable unless the user hosts his site on https. Of course, we can easily load the page up in cheerio and change this ourselves but it may be best to incorporate it into the project. Either way, thank you for the hard work it is appreciated all the way from San Diego, CA!

Thanks,

Trevor

**Comment by s0ph1e** [comment]
Hi Trevor

Thanks for suggestions

I think if resource was not loaded and it has absolute link like `//example.com/some-resource.js` - it is a problem only if someone opens site from file. On serving via http/https it is not a problem - resource will be downloaded from external site.
But if resource was not loaded and it has relative link, for example `./some/image.jpg` - it is a real problem because resource doesn't exist in downloaded site

I have a plan to update not loaded resources with absolute link #123, it will be a solution for both cases

**Comment by s0ph1e** [comment]
Implemented in 3.1.0, using option `updateMissingSources` should help
