### ISSUE TITLE
Scrap site from snapshot

### ISSUE THREAD

**Issue by mrodessit** [s0ph1e/node-website-scraper#181]
It would be very nice, if u can add support to parse local HTML file (or buffer with html data), saved from web.

Example usage: i can make HTML snapshot from website using PhantomJS, SlimerJS or TriffleJS, after script execution and after same actions. Then pass those html to scraper and tell that native url is "http://example.com", so scraper can resolve resources and download them.

I think it is more flexible way to support headless browsers cons.

**Comment by s0ph1e** [comment]
Hi
Thanks for suggestion

I'm not going to support local files because websites should be in internet, not in file system

And if the goal is to download dynamic website - I think saving html to local file and sending it to scraper is workaround. 
More generic solution would be option/plugin to use headless browsers for requests. I'm investigating ways how to implement it in #169
