### ISSUE TITLE
Improper file data with some css and js files

### ISSUE THREAD

**Issue by chadwhitaker** [s0ph1e/node-website-scraper#20]
I noticed when scrapping  [https://dribbble.com/about](https://dribbble.com/about) that the CSS files and some JS files are saved improperly. Below is an example screenshot of a CSS file.

Any idea what is causing this? These files are pulled from Amazon's Cloudfront service and are severed over SSL. 

![screen shot 2016-03-16 at 23 53 00](https://cloud.githubusercontent.com/assets/433078/13836725/3df3a9b6-ebd2-11e5-8cf9-fbba23b7b5e5.png)

**Comment by s0ph1e** [comment]
Hi @chadwhitaker 
Thanks for reporting a bug

The cause is that server returns gzipped response (while header `Accept-Encoding:gzip` was not set in request)
I'm going to add support of gzipped files ([request](https://github.com/request/request) allows it), so fix will be available in version 0.3.3 today

**Comment by s0ph1e** [comment]
website-scraper@0.3.3 is published to npm

**Comment by chadwhitaker** [comment]
Confirmed. Thanks, @s0ph1e!
