### ISSUE TITLE
Failed to scrap tor websites.

### ISSUE THREAD

**Issue by projectkart** [s0ph1e/node-website-scraper#214]
Url: http://tmskhzavkycdupbr.onion/

Trying to scrap above url but it seems getting failed. Below is a script and out put.

var scrape = require('website-scraper');
const phantomHtml = require('website-scraper-phantom');
var Agent = require('socks5-http-client/lib/Agent');

scrape({
  urls: [
    'http://tmskhzavkycdupbr.onion/',
    'http://jzn5w5pac26sqef4.onion'
  ],
  httpResponseHandler: phantomHtml,
  directory: '/home/node/website-scraper/data-warehouse/onion/',
  request: {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0'
     },
        agentClass: Agent,
        agentOptions: {
                        socksHost: 'localhost',
                        socksPort: 9050
         }
  }
}).then(console.log).catch(console.log);

Out Put:
[ Resource {
    url: 'http://tmskhzavkycdupbr.onion/',
    filename: 'index.html',
    type: null,
    depth: 0,
    parent: null,
    children: [],
    saved: false },
  Resource {
    url: 'http://jzn5w5pac26sqef4.onion',
    filename: 'index.html',
    type: null,
    depth: 0,
    parent: null,
    children: [],
    saved: false } ]

**Comment by projectkart** [comment]
It seems like its because of httpResponseHandler: phantomHtml. If we remove this its working perfect.
Is there any way to make it work with phantom as well.

Thanks!

**Comment by s0ph1e** [comment]
Hi @projectkart 

It is not working because `request` option is ignored for phantom handler.

As I understand some proxy settings are needed to render tor website, but for now phantom plugin doesn't support any customizations.  

I have no plans about adding tor support to phantom plugin. But if you have and idea how to do it - feel free to contribute to [website-scraper-phantom](https://github.com/s0ph1e/node-website-scraper-phantom)
