### ISSUE TITLE
node runs out of memory on really large websites

### ISSUE THREAD

**Issue by lschans** [s0ph1e/node-website-scraper#215]
After downloading a large webshop/website the scraper crashes.

My config is:

urls: [scrapeURL],
  directory: scrapeDir,
  maxRecursiveDepth: 3,
  recursive: true,
  ignoreErrors: true,
  filenameGenerator: 'bySiteStructure',
  urlFilter: urlFilter

After like 15 minutes the script crashes with an out of memory error
<--- Last few GCs --->

  800764 ms: Mark-sweep 3773.5 (1435.3) -> 3779.8 (1435.3) MB, 57.0 / 0.0 ms [allocation failure] [scavenge might not succeed].
  800823 ms: Mark-sweep 3779.8 (1435.3) -> 3794.8 (1419.3) MB, 57.9 / 0.0 ms [last resort gc].
  800884 ms: Mark-sweep 3794.8 (1419.3) -> 3809.8 (1419.3) MB, 60.6 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x26a9420cfb39 <JS Object>
    1: fromString(aka fromString) [buffer.js:~187] [pc=0x1d7007ff2bc4] (this=0x26a942004381 <undefined>,string=0x27d4c323f511 <Very long string[106448]>,encoding=0x26a9420f2e41 <String[6]: binary>)
    2: from [buffer.js:~92] [pc=0x1d7007fe8076] (this=0x277af269dc29 <JS Function Buffer (SharedFunctionInfo 0x277af2604ef9)>,value=0x27d4c323f511 <Very long string[106448]>,encodingOrOffset=0x26a942...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteOneByte(unsigned char*, int, int, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: 0x1d7007ea94b8
[1]    9147 abort      node index.js

**Comment by kucukharf** [comment]
**In recursive mode**, somehow you should draw borders for your crawler like whitelist, blacklist for visiting urls. Otherwise, it will crash anyway with out of memory anyway. 

If you are sure about your scraper is visiting what it should visit, you can try to increase nodes executable memory size.

`node --max-old-space-size=1024 app.js // to increase memory 1gb`
`node --max-old-space-size=2048 app.js // to increase memory 2gb`
`node --max-old-space-size=3072 app.js // to increase memory 3gb`
`node --max-old-space-size=4096 app.js // to increase memory 4gb`
`node --max-old-space-size=5120 app.js // to increase memory 5gb`
`node --max-old-space-size=6144 app.js // to increase memory 6gb`
`node --max-old-space-size=7168 app.js // to increase memory 7gb`
`node --max-old-space-size=8192 app.js // to increase memory 8gb`

**Comment by s0ph1e** [comment]
Hi @lschans 

Completely agree with @kucukharf 's suggestion: 
* you should increase memory 
* ensure that you're trying to download only what you need
To track what scraper is doing you can use `debug` [as described in readme](https://github.com/s0ph1e/node-website-scraper#log-and-debug)

Hope it helps. 
If you have more questions - feel free to ask
